apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: nginx
  namespace: gotk-system
spec:
  dependsOn:
    - name: base
  interval: 10m0s
  path: ./nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system
status: {}
